# Generated by Django 3.0.5 on 2021-03-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitchen',
        ),
    ]
