# Generated by Django 3.0.5 on 2021-03-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_kitchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchen',
            old_name='time_out',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='time_in',
            new_name='start_time',
        ),
    ]
