# Generated by Django 3.0.5 on 2021-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0004_auto_20210331_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kitchen_imgs'),
        ),
    ]
