# Generated by Django 3.0.5 on 2021-03-31 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='question_one',
            field=models.CharField(choices=[('What was your childhood nickname?', 'What was your childhood nickname?'), ('What town/city did you live in as a child?', 'What town/city did you live in as a child?'), ('What primary school did you attend?', 'What primary school did you attend?'), ('What high school did you graduate from?', 'What high school did you graduate from?'), ('What is your favorite movie?', 'What is your favorite movie?'), ('What is your favorite song?', 'What is your favorite song?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What is the name of your first pet?', 'What is the name of your first pet?'), ("What is your oldest sibling's name, excluding yourself?", "What is your oldest sibling's name, excluding yourself?")], max_length=80, validators=[django.core.validators.MinLengthValidator(limit_value=20, message='Security question must be at least 20 characters long.'), django.core.validators.MaxLengthValidator(limit_value=80, message='Security question must be at most 80 characters long.'), django.core.validators.RegexValidator(message='Please insert a valid security question.', regex="^[A-Za-z0-9 ,'//]{20,80}\\?$"), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
